//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CButton.h
//  @ Date : 2013/9/12
//  @ Author : 
//
//


#if !defined(_CBUTTON_H)
#define _CBUTTON_H
#include "CForm.h"

class CButton : public CForm {
public:
	CButton();
	CButton(string title, const SMALL_RECT &rect, int type);
	void Show();
	int Input(int key);
	void FocusOn();
	void FocusOff();
protected:
	int m_iFrame;
	bool m_body;
	int m_type;
};

#endif  //_CBUTTON_H
