//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CForm.cpp
//  @ Date : 2013/9/12
//  @ Author : 
//
//


#include "CForm.h"
HANDLE CForm::s_hOut=0;
HANDLE CForm::s_hIn=0;
vector<int> CForm::m_foColorIndex;
vector<int> CForm::m_bkColorIndex;
WORD CForm::foColors[16]={0};
WORD CForm::bkColors[16]={0};
char CForm::chBox[6][7][3];
stack<BufBlock> CForm::buffers;
CForm::CForm() {

}

CForm::CForm(string title,const SMALL_RECT &rect):m_text(title),m_rect(rect) {
}

CForm::~CForm() {

}

void CForm::StartConsole() {
	s_hOut=GetStdHandle(STD_OUTPUT_HANDLE);
	s_hIn=GetStdHandle(STD_INPUT_HANDLE);
	foColors[0] = bkColors[0] = 0;
	foColors[1] = FOREGROUND_BLUE;
	foColors[2] = FOREGROUND_GREEN;
	foColors[3] = FOREGROUND_BLUE |  FOREGROUND_GREEN;
	foColors[4] = FOREGROUND_RED;
	foColors[5] = FOREGROUND_RED |  FOREGROUND_BLUE;
	foColors[6] = FOREGROUND_RED |  FOREGROUND_GREEN;
	foColors[7] = FOREGROUND_RED |  FOREGROUND_GREEN | FOREGROUND_BLUE;
	bkColors[1] = BACKGROUND_BLUE;
	bkColors[2] = BACKGROUND_GREEN;
	bkColors[3] = BACKGROUND_BLUE |  BACKGROUND_GREEN;
	bkColors[4] = BACKGROUND_RED;
	bkColors[5] = BACKGROUND_RED |  BACKGROUND_BLUE;
	bkColors[6] = BACKGROUND_RED |  BACKGROUND_GREEN;
	bkColors[7] = BACKGROUND_RED |  BACKGROUND_GREEN | BACKGROUND_BLUE;
	for (int i=0; i<=7; i++)
	{
		foColors[i+8]  = foColors[i] + FOREGROUND_INTENSITY;
		bkColors[i+8]  = bkColors[i] + BACKGROUND_INTENSITY;
	}
	///////////////////////////////////////////
	MakeFrameWord();
	SMALL_RECT rect={0,0,79,24};
	SetConsoleOutputCP(936);
	COORD size={80,25};
	SetConsoleWindowInfo(s_hOut,TRUE,&rect);
	SetConsoleScreenBufferSize(s_hOut,size);
	SetConsoleTitle("网络爬虫");
	ChgAttribute(CForm::Blue,CForm::White);
}

void CForm::CloseConsole() {
	if (s_hOut)
	{
		CloseHandle(s_hOut);
	}
	
	if (s_hIn)
	{
		CloseHandle(s_hIn);
	}
}

void CForm::ClearWindow(const SMALL_RECT &rect) {
	COORD pos={rect.Left,rect.Top};
	DWORD nWrited;
	CONSOLE_SCREEN_BUFFER_INFO screenInfo;
	GetConsoleScreenBufferInfo(s_hOut,&screenInfo);
	for (int i=0;i<=rect.Bottom-rect.Top;i++)
	{
		FillConsoleOutputAttribute(s_hOut,screenInfo.wAttributes,rect.Right-rect.Left+1,pos,&nWrited);
		FillConsoleOutputCharacter(s_hOut, ' ',rect.Right-rect.Left+1, pos, &nWrited);
		pos.Y++;
	}
	pos.X=rect.Left;pos.Y=rect.Top;
}

void CForm::ShowCursor(bool show) {
	CONSOLE_CURSOR_INFO cursor_info;
	GetConsoleCursorInfo(s_hOut,&cursor_info);
	cursor_info.bVisible=show;
	SetConsoleCursorInfo(s_hOut,&cursor_info);
}

void CForm::ChgAttribute(int bgColor, int fgColor){
 	m_bkColorIndex.push_back(bgColor);
 	m_foColorIndex.push_back(fgColor);
	SetConsoleTextAttribute(s_hOut,bkColors[bgColor] | foColors[fgColor]);
}

bool CForm::RetAttribute(){
	if (m_bkColorIndex.size()==1)
	{
		return FALSE;
	}
	m_bkColorIndex.pop_back();
	m_foColorIndex.pop_back();
	int p=m_foColorIndex.size()-1;
	SetConsoleTextAttribute(s_hOut,foColors[m_foColorIndex[p]] | bkColors[m_bkColorIndex[p]]);
	return true;

}

void CForm::PrintWord(const char * ss,int x,int y){
	COORD pos;
	pos.X=x;pos.Y=y;
	DWORD nWrited;
	WriteConsoleOutputCharacter(s_hOut,ss,strlen(ss),pos,&nWrited);
}
//////////////////////////////////////

void CForm::DrawFrame(int mode) {
	ClearWindow(m_rect);
	PrintWord(chBox[mode][0],m_rect.Left,m_rect.Top);
	for (int i=m_rect.Left+2;i<m_rect.Right-2;i+=2)
	{
		PrintWord(chBox[mode][4],i,m_rect.Top);
	}
	PrintWord(chBox[mode][1],m_rect.Right-1,m_rect.Top);
	PrintWord(chBox[mode][2],m_rect.Left,m_rect.Bottom);
	for (int i=m_rect.Left+2;i<m_rect.Right-2;i+=2)
	{
		PrintWord(chBox[mode][5],i,m_rect.Bottom);
	}
	PrintWord(chBox[mode][3],m_rect.Right-1,m_rect.Bottom);
	for (int i=m_rect.Top+1;i<m_rect.Bottom;i++)
	{
		PrintWord(chBox[mode][6],m_rect.Left,i);
		PrintWord(chBox[mode][6],m_rect.Right-1,i);
	}

}

void CForm::SetCursorPos(int x, int y) {
	assert(x>=0&&x<m_rect.Right-m_rect.Left);
	COORD pos={x+m_rect.Left,y+m_rect.Top};
	SetConsoleCursorPosition(s_hOut,pos);
}

void CForm::GetCursorPos(int &x, int &y) {
	CONSOLE_SCREEN_BUFFER_INFO csbi;
	GetConsoleScreenBufferInfo(s_hOut, &csbi);
	x=csbi.dwCursorPosition.X-m_rect.Left;
	y=csbi.dwCursorPosition.Y-m_rect.Top;
}


void CForm::SetTitle(string title) {
	m_text=title;
}

string CForm::GetTitle() {
	return m_text;
}
//////////////////////////////////////
void CForm::Show() {

}

int CForm::Input(int key) {
	return key;
}

void CForm::PrintTitle(int alignment) {
	COORD pos;
	if (m_text.length() == 0)
	{
		return;
	}
	const char * ss=m_text.c_str();
	int len1,len2,p;
	pos.Y=(m_rect.Top+m_rect.Bottom)/2;
	SMALL_RECT rect={m_rect.Left+2,m_rect.Top+1,m_rect.Right-2,m_rect.Top+1};
	ClearWindow(rect);
	switch (alignment)
	{
	case CForm::Left:
		CForm::PrintWord(ss,m_rect.Left+2,m_rect.Top+1);
		break;
	case CForm::Middle:
		len1=m_rect.Right-m_rect.Left-3;
		len2=strlen(ss);
		p=m_rect.Left+2+(len1-len2)/2;
		CForm::PrintWord(ss,p,m_rect.Top+1);
		p+=2*len2;
		break;
	case CForm::Right:
		len1=m_rect.Right-m_rect.Left-3;
		len2=strlen(ss);
		p=m_rect.Left+2+len1-len2;
		CForm::PrintWord(ss,p,pos.Y);
		break;
	}
}
void CForm::FocusOn(){

}
void CForm::FocusOff(){

}
void CForm::SaveWindow(const COORD &size,const COORD &pos,SMALL_RECT temp){
	BufBlock buf;
	buf.size=size;
	buf.pos=pos;
	buf.rect=temp;
	ReadConsoleOutput(CForm::s_hOut,buf.buffer,size,pos,&(buf.rect));
	buffers.push(buf);
}
void CForm::SaveWindow(){
	SMALL_RECT rect ={0,0,79,24};
	COORD size = {rect.Right - rect.Left + 1 ,rect.Bottom - rect.Top + 1};
	COORD pos ={0,0};
	SaveWindow(size,pos,rect);
}
void CForm::RetWindow(){
	BufBlock&buf=buffers.top();
	WriteConsoleOutput(CForm::s_hOut,buf.buffer,buf.size,buf.pos,&(buf.rect));
	buffers.pop();
}
void CForm::MakeFrameWord(){
	//根据mode的不同值给字符串数组赋值
	strcpy(chBox[0][0],"┌");	// 左上角点
	strcpy(chBox[0][1],"┐");	// 右上角点
	strcpy(chBox[0][2],"└");	// 左下角点
	strcpy(chBox[0][3],"┘");	// 右下角点
	strcpy(chBox[0][4],"─");	// 水平
	strcpy(chBox[0][5],"─");	// 水平
	strcpy(chBox[0][6],"│");	// 坚直
	// 双线
	strcpy(chBox[1][0],"╔");	// 左上角点
	strcpy(chBox[1][1],"╗");	// 右上角点
	strcpy(chBox[1][2],"╚");	// 左下角点
	strcpy(chBox[1][3],"╝");	// 右下角点
	strcpy(chBox[1][4],"═");	// 水平
	strcpy(chBox[1][5],"═");	// 水平
	strcpy(chBox[1][6],"║");	// 坚直
	// 混合, 上下双余单
	strcpy(chBox[2][0],"╒");	// 左上角点
	strcpy(chBox[2][1],"╕");	// 右上角点
	strcpy(chBox[2][2],"╘");	// 左下角点
	strcpy(chBox[2][3],"╛");	// 右下角点
	strcpy(chBox[2][4],"═");	// 水平
	strcpy(chBox[2][5],"═");	// 水平
	strcpy(chBox[2][6],"│");	// 坚直
	// 混合, 上单双余
	strcpy(chBox[3][0],"╒");	// 左上角点
	strcpy(chBox[3][1],"╕");	// 右上角点
	strcpy(chBox[3][2],"└");	// 左下角点
	strcpy(chBox[3][3],"┘");	// 右下角点
	strcpy(chBox[3][4],"═");	// 水平
	strcpy(chBox[3][5],"─");	// 水平
	strcpy(chBox[3][6],"│");	// 坚直
	// 圆角矩形
	strcpy(chBox[4][0],"╭");	// 左上角点
	strcpy(chBox[4][1],"╮");	// 右上角点
	strcpy(chBox[4][2],"╰");	// 左下角点
	strcpy(chBox[4][3],"╯");	// 右下角点
	strcpy(chBox[4][4],"─");	// 水平
	strcpy(chBox[4][5],"─");	// 水平
	strcpy(chBox[4][6],"│");	// 坚直
	// 混合, 左右双余单
	strcpy(chBox[5][0],"╓");	// 左上角点
	strcpy(chBox[5][1],"╖");	// 右上角点
	strcpy(chBox[5][2],"╙");	// 左下角点
	strcpy(chBox[5][3],"╜");	// 右下角点
	strcpy(chBox[5][4],"─");	// 水平
	strcpy(chBox[5][5],"─");	// 水平
	strcpy(chBox[5][6],"║");	// 坚直
	////////////////////////////////////////////

}