//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CLoginForm.h
//  @ Date : 2013/9/12
//  @ Author : 
//
//


#if !defined(_CLOGINFORM_H)
#define _CLOGINFORM_H

#include "CDialogForm.h"
#include "CDialogForm.h"
#include "CButton.h"
#include "CStatic.h"
#include "CEdit.h"
class CLoginForm : public CDialogForm {
public:
	CLoginForm(const string& title,const SMALL_RECT &rect);
	void OnOk();
	void OnCancel();
protected:
	CStatic *userNameLb,*passwordLb;
	CEdit *userNameT,*passwordT;
	CButton *OkBtn,*cancelBtn;
private:
	int errorNum;
};

#endif  //_CLOGINFORM_H
