//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CLoginForm.cpp
//  @ Date : 2013/9/12
//  @ Author : 
//
//



#include "CLoginForm.h"
#include "CMessageBox.h"
#include "COptionsForm.h"
#include "CMainMenuForm.h"
CLoginForm::CLoginForm(const string& title,const SMALL_RECT &rect):CDialogForm(title,rect)
{
	int labelWidth = 11;
	int textFieldWidth = 20;

	int x = (m_rect.Right - labelWidth - textFieldWidth + 1)/2;
	int y = 5;
	SMALL_RECT rect1 = {x,y+1,x+labelWidth,y+1};
	COptionsForm &co=COptionsForm::GetInstance();
	userNameLb = new CStatic("用户名：",rect1);
	m_controls.push_back(userNameLb);
	
	SMALL_RECT rect2 = {rect1.Right+1,rect1.Top-1,rect1.Right+textFieldWidth,rect1.Bottom+1};
	userNameT = new CEdit(co.GetUserName(),rect2,12,0);
	m_controls.push_back(userNameT);

	SMALL_RECT rect3 = {x,rect1.Top+3,x+labelWidth,rect1.Bottom+3};
	passwordLb = new CStatic("密  码：",rect3);
	m_controls.push_back(passwordLb);

	SMALL_RECT rect4 = {rect2.Left,rect2.Top+3,rect2.Right,rect2.Bottom+3};
	passwordT = new CEdit(co.GetUserPassword(),rect4,12,1);
	m_controls.push_back(passwordT);

	SMALL_RECT rect5 = {x,rect4.Top+3,x+labelWidth,rect4.Bottom+3};
	OkBtn = new CButton("确定",rect5,CButton::ID_OK);
	m_controls.push_back(OkBtn);

	SMALL_RECT rect6 = {rect5.Right+12,rect5.Top,rect5.Right+12+labelWidth,rect5.Bottom};
	cancelBtn = new CButton("取消",rect6,CButton::ID_CANCEL);
	m_controls.push_back(cancelBtn);
	m_index = 0;
	errorNum=1;
	m_exit = false;
}

void CLoginForm::OnOk()
{
	string userName = "cjp";
	string password = "cjp";
	if (userNameT->GetTitle() == userName && passwordT->GetTitle() == password)
	{
		SMALL_RECT rect ={0,0,79,24};
		SaveWindow();
		CMainMenuForm menu("主菜单",rect);
		menu.Load(0);
		RetWindow();
	}
	else
	{ 
		if(errorNum>=3){
			CMessageBox::Show("您的登录次数已达三次，请下次再来","提示"); 
			OnCancel();
		}
		CMessageBox::Show("用户名或者密码不正确","提示");
		errorNum++;
	}
}
void CLoginForm::OnCancel()
{
	m_exit=true;
}
