//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : COptionsForm.h
//  @ Date : 2013/9/12
//  @ Author : 
//
//


#if !defined(_COPTIONSFORM_H)
#define _COPTIONSFORM_H
#include <map>
#include <vector>
#include "CDialogForm.h"
#include "CConvert.h"
#include "CButton.h"
#define INI_FILENAME ".\\option.ini"
#define APPNAME "SPIDER"
class COptionsForm : public CDialogForm {
	typedef map<string,string> OptionsMap;
	OptionsMap m_options;
	vector<string>keys;
protected:
	CEdit *nThread,*timeOut,*path,*port,*serverIP,*userName,*passWord;
	COptionsForm();
	static CCriticalSection cs;
	COptionsForm(const COptionsForm&){}
public:
	int Load(int key);
	void OnOk();
	const string &GetValueByKey(const string &key);
	static COptionsForm & GetInstance();
	int GetNthread();
	int GetTimeOut();
	string GetPath();
	int GetPort();
	string GetServerIP();
	string GetUserName();
	string GetUserPassword();
};

#endif  //_COPTIONSFORM_H
