//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CStatic.h
//  @ Date : 2013/9/12
//  @ Author : 
//
//


#if !defined(_CSTATIC_H)
#define _CSTATIC_H

#include "CForm.h"

class CStatic : public CForm {
public:
	void Show();
	int Input(int key);
	CStatic();
	CStatic(string title, const SMALL_RECT &rect);
};

#endif  //_CSTATIC_H
