//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CStatic.cpp
//  @ Date : 2013/9/12
//  @ Author : 
//
//


#include "CStatic.h"

void CStatic::Show() {
	int x=m_rect.Right-m_rect.Left+1-strlen(m_text.c_str());
	PrintWord(m_text.c_str(),m_rect.Left,m_rect.Top);
	string spc="";
	for (int i=0;i<x;i++)
	{
		spc+=' ';
	}
	PrintWord(spc.c_str(),m_rect.Left+strlen(m_text.c_str()),m_rect.Top);
}

int CStatic::Input(int key) {
	return key;
}

CStatic::CStatic() {

}

CStatic::CStatic(string title, const SMALL_RECT &rect):CForm(title,rect) {

}

